version: '3.8'

services:
  spring-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_MAIL_HOST: ${SMTP_HOST}
      SPRING_MAIL_PORT: ${SMTP_PORT}
      SPRING_MAIL_USERNAME: ${SMTP_USERNAME}
      SPRING_MAIL_PASSWORD: ${SMTP_PASSWORD}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: ${SMTP_AUTH}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_ENABLE: ${SMTP_SSL_ENABLE}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: ${SMTP_STARTTTLS_ENABLE}
      API_KEY: ${API_KEY}
      API_TEMPLATE_DIR: /app/templates
    volumes:
      - ${API_TEMPLATE_DIR}:/app/templates
